### ISSUE TITLE
update LECOS to work on QGIS 3.2

### ISSUE THREAD

**Issue by kdarras** [Martin-Jung/LecoS#12] opened 2018-08-29 19:46 UTC
Hi Martin,
it would be awesome if LecoS worked on the newer, excellent QGIS 3.2. Any plans to implement this?

**Comment by Martin-Jung** [comment] 2018-08-29 23:22
Absolutely no time for this at the moment, sorry. I might do it at some point, but it is unlikely in the near future

**Comment by caiohamamura** [comment] 2019-02-20 21:54
I'm working on it and already submitted a pull request, hope it is working fine, you can test it from my fork in the QGIS3 branch.

**Comment by Martin-Jung** [comment] 2019-02-21 01:08
Cheers again for this @caiohamamura Tested it and at most functions in the processing toolbox generally seem to work. Now merged with experimental QGIS3 branch. 

Open issues still:

- [x]  I have not assessed all functionalities of the plugin yet. I uploaded some Lecos testdata here ( http://www.filedropper.com/lecostestdata )
- [x] The GUI under Menu -> Raster -> Landscape ecology does not seem to function anymore. Tested for Landscape statistics and the polygon batch overlay, both of which return Python errors.
- [x] Compared to previous versions, outputs from the Landscape statistics toolset are not automatically added to the ToC anymore. 
- [x] nlmpy functionalities remain untested. Need to update my library before this can be assessed.

**Comment by Martin-Jung** [comment] 2019-02-22 20:29
Hi @caiohamamura,

Great work.
The GUI seems to work now as far as I can see.  The nlmpy algorithms do work as well.
I have not yet tested all algorithms, but found a number of other issues that did not happen before.

- [x] The query raster values tool returns an error that previously did not occur
```
/lecos_sextantealgorithms.py", line 922, in processAlgorithm
lyr = ds.GetLayer()
AttributeError: 'NoneType' object has no attribute 'GetLayer'

```
- [x] The vector overlay returns an error for all algorithms. Probably wrong library connection or similar. Test it out with the data I supplied.
```
Processing algorithm…
Algorithm 'Overlay raster metrics (Polygons)' starting…
Input parameters:
{ 'ADDTABLE' : False, 'CMETRIC' : 1, 'IS_CLASS' : True, 'LAND_GRID' : 'TEST_Lecos.tif', 'LC_CLASS' : 11, 'LMETRIC' : 0, 'OUTPUT_FILE' : 'memory:', 'VECTOR_GRID' : 'test_center.shp' }

Traceback (most recent call last):
File "/home/martin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LecoS/lecos_sextantealgorithms.py", line 856, in processAlgorithm
f = open(output, "wb" )
TypeError: expected str, bytes or os.PathLike object, not NoneType

```
- [x] Something that I found somewhat annoying is that processing created raster files seem to ignore the project CRS, which did not happen before in QGIS 2. Do you happen to know how to query the currently set CRS and set it as default for all created files? At the moment raster files from the Landscape preparation NLMpy toolbox use WGS84 by default

**Comment by caiohamamura** [comment] 2019-02-23 12:56
1. I couldn't reproduce the error ds.GetLayer(), maybe the algorithm should check if vectorLayer is valid
1. Yes, this one could actually be fixed quite easily if we do not need to add the table automatically. I've already commited a fix.
1. Actually I had already changed createRaster within lecos_functions.py to get `QgsProject.instance().defaultCrsForNewLayers().authid()`, I'll check what's going on.

**Comment by caiohamamura** [comment] 2019-02-23 13:12
Oh I see I changed the default behavior of `createRaster`, before it was assigning the epsg of the active layer:

`qgis.utils.iface.activeLayer().crs().authid()`

But I though that maybe there isn't an activeLayer, since the user can actually run the algorithm with no layers in the project at all. Instead it uses the current project epsg.

**Comment by caiohamamura** [comment] 2019-02-23 13:15
Maybe it should check there is an activeLayer selected, if there isn't then get the project crs. What do you think, will it be confusing to the user?

**Comment by Martin-Jung** [comment] 2019-02-25 00:15
Thanks a bunch @caiohamamura for all your help.
Everything seems to work as far as I can see.
I have created a new [release](https://github.com/Martin-Jung/LecoS/releases/tag/LecoS3.0) and uploaded it to the QGIS plugin server from which it should become available soon'ish

Thanks again for your help.

**Comment by Martin-Jung** [comment] 2019-02-25 09:14
It is now available through the QGIS plugin server.

**Closed as completed by Martin-Jung** 2019-02-25 09:14 UTC
